### ISSUE TITLE
Choose a better name and description

### ISSUE THREAD

**Issue by Aminadav** [Aminadav/node-run-middleware#9]
I am not sure that developers understand, what this module do. I think it needs better name & desription & documentation.

Please suggest here for names, and description. 
Thanks

**Comment by awHamer** [comment]
I think the better name would something like "express-run-route" or something close to it.

**Comment by AminaG** [comment]
I think you right

בתאריך 29 בספט 2016 14:02,‏ "Igor Ukolov" <notifications@github.com> כתב:
